#30/8/2022 - Added sports teams and Australian Cities and towns

from datetime import date
import os


#Arugment for the create_spraylist function to get the company name
# NOT LONGER USED BUT MIGHT BE USEFUL LATER
#def get_companyName():
#    return input("Enter company name: ")

#Called from main
def create_spraylist(companyName):


    print("\nCreating wordlist...")
    #Add new passwords in here. No need to worry about case.
    passwords = (companyName,"password", "welcome","secret","letmein","summer","winter","autumn","spring","test","admin","god","monday","tuesday","wednesday","thursday","friday","saturday","sunday","january","february","march","april","may","june","july","august","september","october","november","december","sql","dev","BrisbaneLions","Lions","Carlton","Collingwood","Essendon","Fremantle","Geelong","GoldCoastSuns","GoaldCoast","Giants","Hawthorn","PortAdelaide","Richmond","StKilda","Swans","SydneySwans","Sydney","Eagles","Bulldogs","Broncos","Blues","AbercrombieCaves","Abercrombie","Aberdeen","Adaminaby","Adelaide","Adelong","Agnes","Aireys","Airlie","AirlieBeach","Albany","Albion","Albury","Aldgate","Aldinga","Alexandra","AliceSprings","Alice","Allora","Alpha","Alstonville","Anakie","Andamooka","Angaston","Anglesea","AnsonsBay","Antwerp","Apollo","Appin","Araluen","Aramac","Ararat","Ardlethan","Ardrossan","Ariah","Arkaroola","Arltunga","Armadale","Armidale","Arno","Arthur","Ashford","Atherton","Auburn","Augusta","Austinmer","Australind","Avenel","Avoca","Ayr","BTOP","Babinda","Bacchus","Badgingarra","Bairnsdale","Balaklava","Balingup","Balladonia","Ballarat","Ballina","Balmoral","Balranald","Bamaga","Bangalow","Barcaldine","Barellan","Bargara","Bargo","Barham","Barmah","Barmedman","Barmera","Barooga","Barraba","Barrington","Barringun","Barrow","Barwon","Batchelor","Batemans","Bathurst","Batlow","Baxter","Beachport","Beaconsfield","Beagle","Beaudesert","Beaufort","Bedarra","Beech","Beechworth","Beenleigh","Bega","Belgrave","Bell","Bellingen","Bells","Belmont","Beltana","Bemboka","Benalla","Bencubbin","Bendemeer","Bendigo","Bermagui","Berri","Berridale","Berrigan","Berrima","Berry","Berwick","Bethany","Beulah","Beveridge","Beverley","Bicheno","Biggenden","Biloela","Bilpin","Binalong","Binda","Bindoon","Bingara","Birchip","Birdsville","Birdwood","Blackall","Blackheath","Blackwater","Blackwood","Blanchetown","Blayney","Blinman","Boat","Bodalla","Boddington","Boggabri","Bombala","Bonalbo","Boodjamulla","Booleroo","Booligal","Boonah","Booroorban","Boorowa","Borden","Border","Bordertown","Borroloola","Bothwell","Boulia","Bourke","Bowen","Bowral","Bowraville","Box","Boydtown","Boyup","Braidwood","Branxholm","Branxton","Breadalbane","Bremer","Brewarrina","Bribie","Bridgetown","Bridgewater","Bridport","Bright","Brighton","Brim","Brindabella","Brisbane","Broad","Broadford","Broadwater","Broken","Bronte","Brooklyn","Brookton","Broome","Brooweena","Broulee","Bruce","Brunswick","Bruny","Bruthen","Buchan","Buckland","Buderim","Bulahdelah","Bulli","Bunbury","Bundaberg","Bundanoon","Bundarra","Bundeena","Bungendore","Bungle","Bungonia","Buninyong","Burketown","Burleigh","Burnie","Burning","Burra","Burrawang","Burrinjuck","Bushy","Busselton","Byng","Byrock","Byron","CTOP","Caboolture","Cabramurra","Caiguna","Cairns","Calliope","Caloundra","Camden","Camooweal","Campbell","Campbelltown","Camperdown","Canberra","Candelo","Cann","Canowindra","Jervis","Leveque","Otway","Tribulation","Capel","Capella","Capertee","Captains","Carcoar","Cardwell","Carisbrook","Carnamah","Carnarvon","Carrathool","Carrieton","Casino","Cassilis","Casterton","Castlemaine","Catherine","Cattai","Cecil","Ceduna","Central","Cervantes","Cessnock","Charleville","Charlton","Charters","Chewton","Childers","Chillagoe","Chiltern","Chinchilla","Churchill","Clare","Clarence","Clermont","Cleve","Cleveland","Clifton","Nobby","Cloncurry","Clunes","Coalcliff","Cobar","Cobargo","Cobden","Cobram","cockburn","Cocklebiddy","Coffin","CoffsHarbour","Coffs","Cohuna","Colac","Coleambally","Colebrook","Coledale","Coleraine","Coles","Collector","Collie","Collinsville","Comboyne","Condamine","Condobolin","CooberPedy","Cooktown","Coolah","Coolamon","Coolangatta","Coolgardie","Cooma","Coonabarabran","Coonamble","Coonawarra","Cooranbong","Coorong","Cooroy","Cootamundra","Copley","Coraki","Coral","Corinella","Corinna","Corowa","Corrigin","Corryong","Cossack","Cowell","Cowes","Cowra","CradleMountain","Crafers","Cranbourne","Cranbrook","CrescentHead","Cressy","Creswick","Crookwell","Crows","Croydon","Crystal","Cuballing","Cudal","Cue","Culburra","Culcairn","Cullen","Cummins","Cunderdin","Cunnamulla","Cygnet","DTOP","Daintree","Dalby","Dalgety","Dalwallinu","Daly","DalyWaters","Dampier","DandenongRanges","Dandenong","Darkan","Darlington","Dartmoor","Darwin","Daydream","Daylesford","Deddington","Deloraine","Denham","Deniliquin","Denman","Denmark","Derby","Derwent","Devonport","Dimboola","DirkHartog","Dirk","Donald","Dongara","Donnybrook","Doomadgee","Dorrigo","Double","Dover","Dowerin","Dromana","Drysdale","Duaringa","Dubbo","Dumbleyung","Dunalley","Dunedoo","Dungog","Dunk","Dunkeld","Dunolly","Dunsborough","Durras","Dwellingup","ETOP","EaglehawkNeck","Eaglehawk","Ebenezer","Echuca","Echunga","Eden","Edenhope","Edithburgh","Eidsvold","Eildon","Eldorado","Elliston","Eltham","Emerald","Emmaville","EmuPark","Emu","Eneabba","Enngonia","Erldunda","Esk","Esperance","Eucla","Eudunda","Eugowra","Eulo","Euroa","Euston","Evandale","Evans","Exmouth","FTOP","Falls","Falmouth","Faraway","Faulconbridge","Ferntree","Fingal","Finley","Crossing","Fitzroy","Flinders","Forbes","Forster-Tuncurry","Foster","Fowlers","Franklin","Frankston","Fraser","Island","Fremantle","French","GTOP","Ganmain","Gatton","Gawler","Gayndah","Geelong","Geeveston","Genoa","George","Georgetown","Geraldton","Gerringong","Gerroa","Gilgandra","Gin","Gingin","Girilambone","Gisborne","Gladstone","GlassHouseMountains","Glen","Glenbrook","Glenelg","Glenrowan","Gloucester","Gnowangerup","Gooloogong","Goolwa","Goondiwindi","Gordonvale","Goroke","Gosford","Goulburn","Goulds","Grafton","Grandchester","Grantville","Graytown","Great","Green","Greenbushes","Greenmount","Greenock","Greenough","Gregory","Grenfell","Gresford","Greta","Griffith","Guildford","Gulargambone","Gulgong","Gumeracha","Gundagai","Gundy","Gunnedah","Gunning","Guyra","Gwalia","Gympie","HTOP","Hadspen","Hahndorf","HallsCreek","Halls","Hamilton","Harcourt","Harden","Harrietville","Harrington","Harrow","Hartley","Harvey","Hastings","Hat","Hawker","Hawks","Hay","Hazelbrook","Healesville","Heathcote","Heidelberg","Henty","Hepburn","Herberton","Hermannsburg","Heron","Hervey","Heyfield","Heywood","Hill","Hillgrove","Hillston","Hinchinbrook","Hinton","Hobart","Holbrook","Hopetoun","Horizontal","Horrocks","Horsham","Houtman","Howard","Howlong","Hughenden","Humpty","Hungerford","Huskisson","Hyden","ITOP","Ilfracombe","Iluka","Ingham","Inglewood","Injune","Innamincka","Innisfail","Inverell","Inverloch","Ipswich","Iron","Irvinebank","Isisford","JTOP","Jamberoo","Jamestown","Jamieson","Jandowae","Jenolan","Jeparit","Jericho","Jerilderie","Jerramungup","Jerrys","Jimbour","Jindabyne","Jindera","Joadja","Jondaryan","Jugiong","Julia","Junee","Jurien","KTOP","Kadina","Kakadu","Kalamunda","Kalbarri","Kalgoorlie","Kallista","Kalorama","Kambalda","Kameruka","Kandos","KangarooIsland","Kangaroo","Kaniva","Kanowna","Kapunda","Karoonda","Karratha","Karuah","Karumba","Katanning","Katherine","Katoomba","Keilor","Keith","Kellerberrin","Kempsey","Kempton","Kendall","Kenilworth","Kerang","Kettering","Khancoban","Kiama","Kiandra","Kilcoy","Kilkivan","Killarney","Kilmore","Kimba","Kincumber","King","Kings","Kingaroy","Kinglake","KingsCanyon","Canyon","Kingscliff","Kingston","Kojonup","Kondinin","Koo","Koondrook","Koonya","Koorawatha","Koorda","Koroit","Korumburra","Kulin","Kununurra","Kuranda","Kurnell","Kurrajong","Kurri","Kwinana","Kyabram","Kyneton","Kyogle","LTOP","LadyElliot","Elliot","Laidley","Argyle","Bolac","Cargelligo","Condah","Grace","Macquarie","Mungo","StClair","Tyers","Entrance","Lancefield","Lancelin","Landsborough","Larrimah","Lascelles","Latrobe","Launceston","Laura","Laurieton","Lavers","Laverton","Lawn","Lawson","Leeman","Leeton","Leigh","Lennox","Leongatha","Leonora","Leura","Licola","Lightning","Lilydale","Lismore","Lithgow","Lizard","Lobethal","Lockhart","Longford","Longreach","Lord","Lorne","Louth","Loxton","Lucknow","Lyndhurst","Lyndoch","MTOP","Macarthur","Mackay","Macksville","Maclean","Madura","Maffra","Magnetic","Maitland","Majors","Malanda","Maldon","Maleny","Mallacoota","Mallala","Malmsbury","Mandurah","Manildra","Manilla","Manjimup","Mannum","Mansfield","Marble","Mareeba","Margaret","Maria","Marion","Marlborough","Marlo","Maroochydore","Marrawah","Marree","Marulan","Maryborough","Marysville","Mataranka","Mathoura","McKinlay","McLaren","Medlow","Meekatharra","Megalong","Melrose","Melton","Melville","Mendooran","Menindee","Meningie","Menzies","Merimbula","Merino","Merredin","Merriwa","Merriwagga","Metung","Milang","Milawa","Mildura","Miles","Millaa","Millicent","Millmerran","Millthorpe","Milparinka","Milton","Mingenew","Minlaton","Minnipa","Mintaro","Minyip","Mirani","Mirboo","Mission","MittaMitta","Mitta","Mittagong","Moama","Moe","Mogo","Mole","Moliagul","Mollymook","Molong","Monbulk","MonkeyMia","Monkey","Monto","Moonta","Moora","Mooroopna","Moranbah","Morawa","Moree","Moreton","Morgan","Morisset","Mornington","Morpeth","Mortlake","Moruya","Morwell","MossVale","Mossman","Moulamein","Augustus","Barker","Baw","Beauty","Buffalo","Buller","Gambier","Garnet","Hotham","Isa","Kosciuszko","Macedon","Magnet","Molloy","Perry","Pleasant","Surprise","Victoria","Wilson","Moura","Mourilyan","Mudgee","Mullewa","Mullumbimby","Mundaring","Mundrabilla","Mundubbera","Mungindi","Murchison","Murgon","Murray","Murrayville","Murringo","Murrumbateman","Murrumburrah","Murrurundi","Murtoa","Murwillumbah","Muswellbrook","Muttaburra","Myall","Mylor","Myrtleford","NTOP","Nabiac","Nagambie","Nambour","Nambucca","Nanango","Nannup","Naracoorte","Narembeen","Narooma","Narrabri","Narrandera","Narrogin","Narromine","Nathalia","Natimuk","NationalPark","Nelligen","NelsonBay","Nelson","Nerang","NewNorcia","Norcia","NewNorfolk","Norfolk","Newcastle","Newhaven","Newman","Newnes","Nhill","Nimbin","Nimmitabel","Noojee","Noosa","Norah","Normanton","Norseman","Northam","Northampton","Northcliffe","Nowra","Nullagine","Nullarbor","Numurkah","Nundle","Nungarin","Nuriootpa","Nyngan","OTOP","Oakey","Oatlands","Oberon","OceanGrove","Olinda","Omeo","Ongerup","Onslow","Oodnadatta","Ophir","OraBanda","Orange","Orbost","Orford","Orpheus","Orroroo","Ouyen","PTOP","PacificPalms","Padthaway","PalmBeach","PalmerRiver","Pambula","Pannawonica","Paraburdoo","Parachilna","Paringa","Parkes","Patchewollock","Paterson","Patonga","Paynesville","PeakHill","PearlBeach","Pemberton","Penguin","Penola","Penong","Penrith","Penshurst","Penwortham","Perenjori","Perisher","Perth","Peterborough","Phillip","Picton","Pine","Pingelly","Pinjarra","PittTown","Poatina","PointLonsdale","Pokolbin","Pontville","Pooncarie","Albert","Broughton","Douglas","Essington","Fairy","Germein","Hedland","Lincoln","MacDonnell","Neill","Noarlunga","Pirie","Stephens","Vincent","Wakefield","Welshpool","Portarlington","Portland","Portsea","Powelltown","Prevelly","PrincessMargaret","Proserpine","Proston","Puckapunyal","Pyramid","QTOP","Quairading","Queanbeyan","Queenscliff","Queenstown","Quilpie","Quirindi","Quorn","RTOP","Railton","RainbowBeach","Rainbow","Ravenshoe","Ravensthorpe","Ravenswood","Raymond","RedCliffs","Redcliffe","Renmark","Renner","Richmond","Riverton","Robe","Robertson","Robinvale","Rockhampton","Rockingham","Rockley","Roebourne","Rokeby","Rolleston","Roma","Romsey","Rosebery","Rosebud","Rosevears","Rosewood","Roseworthy","Ross","Rottnest","Roxby","Royal","Rubyvale","Rupanyup","Rushworth","Rutherglen","Rylstone","STOP","Sale","Saltwater","SanRemo","Sandstone","Sarina","Savage","Sawtell","Scone","ScottsHead","Scottsdale","Sea","SealRocks","Seaspray","Seppeltsfield","Serviceton","Sevenhill","SeventeenSeventy","Seymour","Shark","Sheep","Sheffield","Shellharbour","Shepparton","Sherbrooke","Shoalhaven","Shoreham","Shute","Sidmouth","Silo","Silverton","Singleton","Skipton","Smeaton","Smythesdale","Snowtown","Sofala","Somers","Sorell","Sorrento","South","Southern","Southport","Springsure","Springton","Springwood","Albans","Arnaud","GeorgesBasin","Helens","Marys","Stanley","Stansbury","Stanthorpe","Stanwell","Stawell","Steiglitz","Stockton","Stradbroke","Strahan","Stratford","Strathalbyn","Strathmerton","Streaky","Stroud","Stuart","Surat","Surfers","Paradise","SurfersParadise","Sussex","SuttonForest","Swan","Swansea","TTOP","Tailem","Talbingo","Talbot","Tallangatta","Tambo","Tamborine","Tammin","Tamworth","Tanami","Tanunda","Taralga","Taranna","Tarcutta","Taree","Tarlee","Tarnagulla","Taroom","Tarraleah","Tathra","Tatura","Taylors","TeaGardens","Temora","Tennant","Tenterfield","Terang","Terowie","Terrigal","Texas","Thargomindah","Oaks","Rock","Theodore","Thirlmere","Thirroul","Thredbo","ThreeSprings","Thursday","Ti","Tibooburra","TimberCreek","Timboon","TinCanBay","Tinaroo","Tintaldra","Tintinara","Tocumwal","TomPrice","Toodyay","Toora","Tooradin","Toowoomba","Toronto","Torquay","Toukley","Townsville","Trangie","Traralgon","Trentham","Truro","Tuena","Tully","Tumbarumba","Tumby","Tumut","Tunbridge","Tuross","Tweed","UTOP","Ulladulla","Ulmarra","Uluru","Ayers","Ulverstone","Undara","Ungarie","Uralla","Urana","Urbenville","Urunga","VTOP","Venus","Victor","Violet","WTOP","Wagga","WaggaWagga","Wagin","Wahgunyah","Waikerie","Walcha","Walgett","Walhalla","WallaWalla","Walla","Wallabadah","Wallangarra","Wallaroo","Wallerawang","Walpole","Wangaratta","Wangi","WangiWangi","Wanneroo","Waratah","Warburton","Warialda","Warmun","Warooka","Waroona","Warracknabeal","Warragul","Warrandyte","Warren","Warrnambool","Warwick","Watervale","Wauchope","Wedderburn","WeeJasper","WeeWaa","Weipa","Weldborough","Wellington","Wentworth","Werribee","Werris","West","Westbury","Westonia","Whim","White","Whitfield","Whitsundays","Whyalla","Wickepin","Wickham","Wilberforce","Wilcannia","Williams","Williamstown","Willunga","Wilmington","Wilmot","Wilpena","Wilsons","Wiluna","Winchelsea","Windermere","Windeyer","Windsor","Wingham","Winton","Wiseman","Wittenoom","Wollombi","Wollongong","Wombarra","Wombeyan","Wondai","Wongan","Wonthaggi","Woodbridge","Woodburn","Woodenbong","Woodend","Woodford","Woolgoolga","Wooli","Woomera","WoyWoy","Woy","Wudinna","Wyalkatchem","Wycheproof","Wyndham","Wynyard","Wyong","YTOP","Yackandandah","Yalgoo","Yallingup","Yamba","Yambuk","Yanchep","Yandina","Yankalilla","Yarra","YarraGlen","YarraJunction","Yarram","Yarrangobilly","Yarrawonga","Yass","Yea","Yeoval","Yeppoon","Yerranderie","York","Yorketown","Young","Yungaburra","ZTOP","Zeehan")
    current_year = date.today().year

    with open("temp.txt", 'w') as f:
    
        #Formatting for each word in the list
        for x in passwords:
            ##########################
            ##Uppercase first letter##
            ##########################
            f.write(x.capitalize() + "\n")
            f.write(x.capitalize() + "1\n")
            f.write(x.capitalize() + "!\n")
            f.write(x.capitalize() + "123\n")
            f.write(x.capitalize() + "123!\n")
            f.write(x.capitalize() + str(current_year) + "\n")
            f.write(x.capitalize() + str(current_year -1) + "\n")
            f.write(x.capitalize() + str(current_year -2) + "\n")
            f.write(x.capitalize() + str(current_year) + "!\n")
            f.write(x.capitalize() + str(current_year -1) + "!\n")
            f.write(x.capitalize() + str(current_year -2) + "!\n")
            f.write(x.capitalize() + str(current_year -2000) + "\n")
            f.write(x.capitalize() + str(current_year -2001) + "\n")
            f.write(x.capitalize() + str(current_year -2002) + "\n")
            f.write(x.capitalize() + str(current_year -2000) + "!\n")
            f.write(x.capitalize() + str(current_year -2001) + "!\n")
            f.write(x.capitalize() + str(current_year -2002) + "!\n")
            #Replace the letter "a" with "4"
            f.write(x.capitalize().replace("a","4") + "\n")
            f.write(x.capitalize().replace("a","4") + "1\n")
            f.write(x.capitalize().replace("a","4") + "!\n")
            f.write(x.capitalize().replace("a","4") + "123\n")
            f.write(x.capitalize().replace("a","4") + "123!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2002) + "!\n")
            #Replace the letter "a" with "@"
            f.write(x.capitalize().replace("a","@") + "\n")
            f.write(x.capitalize().replace("a","@") + "1\n")
            f.write(x.capitalize().replace("a","@") + "!\n")
            f.write(x.capitalize().replace("a","@") + "123\n")
            f.write(x.capitalize().replace("a","@") + "123!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2002) + "!\n")
            #Replace the letter "s" with 5
            f.write(x.capitalize().replace("s","5") + "\n")
            f.write(x.capitalize().replace("s","5") + "1\n")
            f.write(x.capitalize().replace("s","5") + "!\n")
            f.write(x.capitalize().replace("s","5") + "123\n")
            f.write(x.capitalize().replace("s","5") + "123!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2002) + "!\n")
            #Replace the letter "i" with 1
            f.write(x.capitalize().replace("i","1") + "\n")
            f.write(x.capitalize().replace("i","1") + "1\n")
            f.write(x.capitalize().replace("i","1") + "!\n")
            f.write(x.capitalize().replace("i","1") + "123\n")
            f.write(x.capitalize().replace("i","1") + "123!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3
            f.write(x.capitalize().replace("e","3") + "\n")
            f.write(x.capitalize().replace("e","3") + "1\n")
            f.write(x.capitalize().replace("e","3") + "!\n")
            f.write(x.capitalize().replace("e","3") + "123\n")
            f.write(x.capitalize().replace("e","3") + "123!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2002) + "!\n")
            #Replace the letter "t" with 7
            f.write(x.capitalize().replace("t","7") + "\n")
            f.write(x.capitalize().replace("t","7") + "1\n")
            f.write(x.capitalize().replace("t","7") + "!\n")
            f.write(x.capitalize().replace("t","7") + "123\n")
            f.write(x.capitalize().replace("t","7") + "123!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2002) + "!\n")
            #Replace the letter "o" with 
            f.write(x.capitalize().replace("o","0") + "\n")
            f.write(x.capitalize().replace("o","0") + "1\n")
            f.write(x.capitalize().replace("o","0") + "!\n")
            f.write(x.capitalize().replace("o","0") + "123\n")
            f.write(x.capitalize().replace("o","0") + "123!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3, "a" with "@", "i" with "1", "s" with "5", "o" with "0"
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "1\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3, "a" with "4", "i" with "1", "s" with "5", "o" with "0"
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "1\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "!\n")
            ##########################
            ##Lowercase first letter##
            ##########################
            f.write(x.lower() + "\n")
            f.write(x.lower() + "1\n")
            f.write(x.lower() + "!\n")
            f.write(x.lower() + "123\n")
            f.write(x.lower() + "123!\n")
            f.write(x.lower() + str(current_year) + "\n")
            f.write(x.lower() + str(current_year -1) + "\n")
            f.write(x.lower() + str(current_year -2) + "\n")
            f.write(x.lower() + str(current_year) + "!\n")
            f.write(x.lower() + str(current_year -1) + "!\n")
            f.write(x.lower() + str(current_year -2) + "!\n")
            f.write(x.lower() + str(current_year -2000) + "\n")
            f.write(x.lower() + str(current_year -2001) + "\n")
            f.write(x.lower() + str(current_year -2002) + "\n")
            f.write(x.lower() + str(current_year -2000) + "!\n")
            f.write(x.lower() + str(current_year -2001) + "!\n")
            f.write(x.lower() + str(current_year -2002) + "!\n")
            #Replace the letter "a" with "4"
            f.write(x.lower().replace("a","4") + "\n")
            f.write(x.lower().replace("a","4") + "1\n")
            f.write(x.lower().replace("a","4") + "!\n")
            f.write(x.lower().replace("a","4") + "123\n")
            f.write(x.lower().replace("a","4") + "123!\n")
            f.write(x.lower().replace("a","4") + str(current_year) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -1) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -2) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -2002) + "!\n")
            #Replace the letter "a" with "@"
            f.write(x.lower().replace("a","@") + "\n")
            f.write(x.lower().replace("a","@") + "1\n")
            f.write(x.lower().replace("a","@") + "!\n")
            f.write(x.lower().replace("a","@") + "123\n")
            f.write(x.lower().replace("a","@") + "123!\n")
            f.write(x.lower().replace("a","@") + str(current_year) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -1) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -2) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -2002) + "!\n")
            #Replace the letter "s" with "5"
            f.write(x.lower().replace("s","5") + "\n")
            f.write(x.lower().replace("s","5") + "1\n")
            f.write(x.lower().replace("s","5") + "!\n")
            f.write(x.lower().replace("s","5") + "123\n")
            f.write(x.lower().replace("s","5") + "123!\n")
            f.write(x.lower().replace("s","5") + str(current_year) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -1) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -2) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -2002) + "!\n")
            #Replace the letter "i" with "I"
            f.write(x.lower().replace("i","1") + "\n")
            f.write(x.lower().replace("i","1") + "1\n")
            f.write(x.lower().replace("i","1") + "!\n")
            f.write(x.lower().replace("i","1") + "123\n")
            f.write(x.lower().replace("i","1") + "123!\n")
            f.write(x.lower().replace("i","1") + str(current_year) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -1) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -2) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with "3"
            f.write(x.lower().replace("e","3") + "\n")
            f.write(x.lower().replace("e","3") + "1\n")
            f.write(x.lower().replace("e","3") + "!\n")
            f.write(x.lower().replace("e","3") + "123\n")
            f.write(x.lower().replace("e","3") + "123!\n")
            f.write(x.lower().replace("e","3") + str(current_year) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -1) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -2) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -2002) + "!\n")
            #Replace the letter "t" with "7"
            f.write(x.lower().replace("t","7") + "\n")
            f.write(x.lower().replace("t","7") + "1\n")
            f.write(x.lower().replace("t","7") + "!\n")
            f.write(x.lower().replace("t","7") + "123\n")
            f.write(x.lower().replace("t","7") + "123!\n")
            f.write(x.lower().replace("t","7") + str(current_year) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -1) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -2) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -2002) + "!\n")
            #Replace the letter "o" with "0"
            f.write(x.lower().replace("o","0") + "\n")
            f.write(x.lower().replace("o","0") + "1\n")
            f.write(x.lower().replace("o","0") + "!\n")
            f.write(x.lower().replace("o","0") + "123\n")
            f.write(x.lower().replace("o","0") + "123!\n")
            f.write(x.lower().replace("o","0") + str(current_year) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -1) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -2) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3, "a" with "@", "i" with "1", "s" with "5", "t" with "7", "o" with "0"
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "1\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3, "a" with "4", "i" with "1", "s" with "5", "t" with "7", "o" with "0"
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "1\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "!\n")
    f.close()

#Called from main after the temporary list has been created. Duplicates are created when there are no letters to replace so the word gets created anyway without any modifications
#This reads the temp.txt file and removes the duplicates then saves the new file as spray-list.txt
def remove_duplicates(inFileName,companyName):
    print("Removing duplicates...")
    lines_seen = set()#holds lines already seen
    outfile = open("spray-list.txt", "w")
    for line in open(inFileName, "r"):
        if line not in lines_seen:#not a duplicate
            outfile.write(line)
            lines_seen.add(line)
    outfile.close()


if __name__ == '__main__':
    #Create password spray file with the company name as input
    companyName = input("\nEnter company name: ")
    create_spraylist(companyName)
    
    #Remove any Duplicates
    remove_duplicates("temp.txt",companyName)
    
    #Delete temp file
    print("Deleting temporary file...")
    os.remove("temp.txt")
    
    print("\nWordlist successfully created in: " + os.path.abspath(os.getcwd()) + "\\spray-list.txt\n")
